- name: Deploy to Cloudflare Pages
  uses: docker://cloudflare/cloudflare-pages-action:1.4.0

on:
  push:
    branches:
      - main  # Change this to your main branch name
  pull_request:
    branches:
      - main  # Change this to your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install dependencies
        run: npm install

      - name: Build application
        run: hugo  # Replace this with your build command
      
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/cloudflare-pages-action@1.4.0
        with:
          token: ${{ secrets.CLOUDFLARE_API_TOKEN }}  # Set up this secret in your repository settings
          site-id: 26202fb3dd1d9659b62c758ed55b7627 # Replace this with your Cloudflare Pages site ID
          directory: public # Replace this with your build output directory
